import {
  ArrowDownIcon,
  DiscordLogoIcon,
  EyeClosedIcon,
  FaceIcon,
  Half2Icon,
  TriangleLeftIcon,
  EyeOpenIcon,
  TriangleRightIcon,
  MagicWandIcon,
  TriangleDownIcon,
  ChatBubbleIcon
} from '@radix-ui/react-icons'
import {
  ActivitySquare,
  ALargeSmall,
  AlignLeft,
  ArrowDown,
  ArrowUpDown,
  ArrowUpRight,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleHelp,
  CircleX,
  Clock,
  CheckCircle2,
  CreditCard,
  Database,
  Delete,
  Ellipsis,
  Eye,
  FileSearch,
  FileText,
  Globe,
  IdCard,
  Key,
  KeyRound,
  Layers,
  LoaderCircle,
  LogOut,
  Mail,
  MessageCircleMore,
  Moon,
  Pen,
  Play,
  Plus,
  RefreshCcw,
  Rocket,
  ScanText,
  Search,
  Settings2,
  ShieldCheck,
  Sun,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  ToggleRight,
  Trash2,
  User,
  Users,
  X,
  BookOpen,
  Building2,
  Dot,
  Send,
  ArrowRight,
  User2,
  Info,
  MoreVertical,
  ArrowBigDownDash,
  ArrowBigUpDash,
  ChartColumnIncreasing,
  Hammer,
  ExternalLink,
  Copy,
  Smile,
  WifiOffIcon,
  MessagesSquare,
  ArrowLeft,
  CalendarDays,
  WorkflowIcon,
  CornerDownRight,
  ChevronUp,
  Download
} from 'lucide-react'

import {
  DashboardIcon,
  GitHubIcon,
  GoogleIcon,
  ReloadIcon,
  ChatBubble,
  ActiveSidebarIcon,
  Avatar,
  ScanFace,
  RadioButton,
  SystemIcon,
  UserFace,
  OpenAILogo,
  Pencil,
  Agent,
  ToolIcon,
  MistralLogo,
  GeminiLogo,
  OllamaLogo,
  AzureLogo,
  AnthropicLogo,
  GroqLogo,
  FireworksLogo,
  CohereLogo,
  DeepseekLogo,
  AwsLogo,
  XaiLogo,
  DragIcon,
  SheetIcon,
  Context,
  ReasoningIcon
} from './custom-icons'
import { type IconTypeMap } from './types'

export const ICONS: IconTypeMap = {
  run: Play,
  GitHub: GitHubIcon,
  Google: GoogleIcon,
  dashboard: DashboardIcon,
  activity: ActivitySquare,
  datasets: Layers,
  playground: ChatBubble,
  settings: Settings2,
  legal: FileText,
  Discord: DiscordLogoIcon,
  documentation: BookOpen,
  time: Clock,
  reload: ReloadIcon,
  show: ToggleRight,
  hide: ToggleLeft,
  viewMode: ALargeSmall,
  details: AlignLeft,
  evaluation: FileSearch,
  prompt: MessageCircleMore,
  'human-review': ScanText,
  empty: CircleX,
  instructions: CircleHelp,
  'caret-left': ChevronLeft,
  'caret-right': ChevronRight,
  'caret-down': ChevronDown,
  'caret-up': ChevronUp,
  'eye-closed': EyeClosedIcon,
  'eye-open': EyeOpenIcon,
  copy: Copy,
  activeSidebar: ActiveSidebarIcon,
  avatar: Avatar,
  'scan-face': ScanFace,
  loader: LoaderCircle,
  sort: ArrowUpDown,
  'user-face': UserFace,
  'radio-button': RadioButton,
  api: KeyRound,
  'arrow-up': ArrowUpRight,
  close: X,
  check: Check,
  billingCycle: RefreshCcw,
  refresh: RefreshCcw,
  support: Mail,
  downgrade: ArrowDown,
  data: Database,
  calendar: Calendar,
  user: User,
  team: Users,
  workspace: Building2,
  error: CircleAlert,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  read: Eye,
  write: Pen,
  admin: ShieldCheck,
  delete: Delete,
  userInfo: IdCard,
  name: MessageCircleMore,
  billing: CreditCard,
  create: Plus,
  ellipsisHorizontal: Ellipsis,
  permission: Key,
  review: Search,
  rocket: Rocket,
  trash: Trash2,
  globe: Globe,
  'triangle-left': TriangleLeftIcon,
  'triangle-right': TriangleRightIcon,
  'triangle-down': TriangleDownIcon,
  logout: LogOut,
  sun: Sun,
  moon: Moon,
  half2: Half2Icon,
  tool: ToolIcon,
  system: SystemIcon,
  dot: Dot,
  send: Send,
  'arrow-right': ArrowRight,
  'user-2': User2,
  info: Info,
  'more-vertical': MoreVertical,
  'open-ai': OpenAILogo,
  mistral: MistralLogo,
  gemini: GeminiLogo,
  aws: AwsLogo,
  azure: AzureLogo,
  anthropic: AnthropicLogo,
  groq: GroqLogo,
  fireworks: FireworksLogo,
  deepseek: DeepseekLogo,
  cohere: CohereLogo,
  ollama: OllamaLogo,
  xai: XaiLogo,
  'arrow-big-down-dash': ArrowBigDownDash,
  'arrow-big-up-dash': ArrowBigUpDash,
  'bar-chart-4': ChartColumnIncreasing,
  hammer: Hammer,
  'arrow-down': ArrowDownIcon,
  'external-link': ExternalLink,
  pencil: Pencil,
  face: FaceIcon,
  smile: Smile,
  'magic-wand': MagicWandIcon,
  agent: Agent,
  'wifi-off': WifiOffIcon,
  'messages-square': MessagesSquare,
  reasoning: ReasoningIcon,
  drag: DragIcon,
  'chat-bubble': ChatBubbleIcon,
  'arrow-left': ArrowLeft,
  sheet: SheetIcon,
  'calendar-days': CalendarDays,
  context: Context,
  search: Search,
  'check-circle-2': CheckCircle2,
  workflow: WorkflowIcon,
  'chevron-down': TriangleDownIcon,
  'corner-down-right': CornerDownRight,
  download: Download
}
